### ISSUE TITLE
Fixing wiki's US viewers

### ISSUE THREAD

**Issue by kaustubhhiware** [kaustubhhiware/rose#10]
As pointed out by @Harsh5557,  as of Dec 12 2018, the wiki flag is broken. This is probably due to a change in formatting on wikipedia's side, and needs to be fixed urgently. 

This is a high priority issue. This is relatively easy, the variables need to be printed out and seems to be a 2-3 hour task once an understanding of the code and wikipedia's relevant page is obtained.

Recreation:
```py
$ python scrape_views.py -w -a -s "Two and a half men"
Detected wiki link: https://en.wikipedia.org/wiki/List_of_Two_and_a_Half_Men_episodes
Number of seasons 12
Season  1
		Episode 1
Traceback (most recent call last):
  File "/home/kaustubh/GitHub/rose/scrape_views.py", line 302, in <module>
    views, average = wikiscrape(wikiurl)
  File "/home/kaustubh/GitHub/rose/scrape_views.py", line 87, in wikiscrape
    numviews = float(filter(None, re.findall(floating_point, views))[0])
TypeError: 'filter' object is not subscriptable
```

**Comment by kaustubhhiware** [comment]
Another fix to be added here is line 84 has to be resolved to:
```py
            if len(found) == 0: # updated from ">" to "=="
                episodeviews = '-'
```

**Comment by kunalnpandey** [comment]
After Replacing numviews with 
numviews = float([ _f for _f in re.findall(floating_point, views) if _f ][0]) I am not getting the error.

**Comment by kaustubhhiware** [comment]
That's great !
Would you like to submit a PR for this, once your existing work is merged ?

**Comment by kunalnpandey** [comment]
Yeah Sure.
