### ISSUE TITLE
Add A CONTRIBUTING.MD

### ISSUE THREAD

**Issue by s-ankur** [kaustubhhiware/rose#17]
To avoid problems like #15  with new contributors, I think we should add a contributors md or add something to the readme or maybe add a pull request template

**Comment by kaustubhhiware** [comment]
That would be highly appreciated.
 The file you're looking for is CONTRIBUTING.MD, not CONTRIBUTORS.MD 

You can have a look at the template in one of my previous projects [here](https://github.com/kaustubhhiware/NotiFyre/blob/master/CONTRIBUTING.md), you need to make a few changes in the project url, and communication channel, and a mention for the same in the README, that should suffice. 

Assigning this issue to you right away.
