### ISSUE TITLE
Implementing a webapp

### ISSUE THREAD

**Issue by kaustubhhiware** [kaustubhhiware/rose#4]
Currently, we only have a script that runs on your system. It would be great if the implementation could be shifted to a webapp, based on flask or any light weight framework.

This is of highest priority.

**Comment by Harsh5557** [comment]
I would like to work on it.

**Comment by kaustubhhiware** [comment]
Hi @Harsh5557, what would be your choice of framework? Have you had some experience in developing webapps on python? 

Note that we don't need another implementation of scrape_views.py, we just need to smartly reuse it.

I'll assign this issue to you shortly.

**Comment by Harsh5557** [comment]
Flask 
I do not have prior experience with developing webapps on python but  have worked on python for some time and can learn about webapps development.

**Comment by kaustubhhiware** [comment]
Alright, then go for it. Please share an approximate deadline (3 days, 5 days, a week or whatever ) by which you expect to complete this. Take your time, that's not a problem. Assigning this issue to you.

**Comment by Harsh5557** [comment]
Would it be fine if I take around 10 days ? But will try to do it as early as possible.

**Comment by kaustubhhiware** [comment]
Not a problem.

**Comment by Harsh5557** [comment]
The wikiscrape function does not seem to work.

**Comment by Harsh5557** [comment]
![img](https://user-images.githubusercontent.com/45585853/49849608-6f908f00-fe00-11e8-90fc-c017410aeecb.PNG)

**Comment by kaustubhhiware** [comment]
Could it be due to python version?
Rose was written with Python3 in mind, so please try running the script again with Python 3, I don't think that should give you any issues.

**Comment by Harsh5557** [comment]
![img](https://user-images.githubusercontent.com/45585853/49857893-9ad3a800-fe19-11e8-9504-00aef0bc3b56.PNG)

**Comment by Harsh5557** [comment]
sorry for being ignorant.
Ok i will implement the imdb related functions for the webapp.

**Comment by kaustubhhiware** [comment]
From the looks of it, your code is on your server, you need to manually make a Pull Request on your own repository to this repo. Go to [Harsh5557/rose](https://github.com/Harsh5557/rose) and make a PR. We can proceed further accordingly.

**Comment by Harsh5557** [comment]
I made corrections to the pull request #19 .

**Comment by kaustubhhiware** [comment]
No need to comment on the issue, I get notified as soon as you update the PR as well.
