### ISSUE TITLE
Star cast of a show

### ISSUE THREAD

**Issue by kunalnpandey** [kaustubhhiware/rose#9]
Well one can also ask about the star cast of a show so why not modify the code a little bit to get the details.

**Comment by kaustubhhiware** [comment]
Thanks for pointing this out. I don't think we should close the issue just yet. #7 can be changed based on this.

The cast fetched here would be for the general show, whereas #7 focuses on cast in a particular episode only.

I think a `-c` or  `--cast` flag would be appropriate for this.
Usage: `python scrape_views.py -c "Two and a half men" `

This should fetch the general cast, either from imdb or wikipedia.

**Comment by kaustubhhiware** [comment]
Sure, go right ahead.

**Comment by kunalnpandey** [comment]
![star cast](https://user-images.githubusercontent.com/34450182/49886871-ca59d300-fe60-11e8-8bfe-ff7badb0b2b9.png)
Well This is the Sample output of the modified code

**Comment by kaustubhhiware** [comment]
Nice !
If you're fetching this information from imdb, do you think we should include the number of episodes the actor has starred in as well ?

That is, would you prefer the current system or 
```
List of Top Casts of the Show:
1. Charlie Sheen            ( 178 episodes )
2. Jon Cryer                   ( 262 episodes )
.... 
```
?

I'm not sure which would look good, since you're the contributor what do you think ?

**Comment by kunalnpandey** [comment]
Currently I am fetching data from wikipedia.
And If an user ask about casting of a show he generally means the lead actors of the show .So I think  above information would be adequate to satisfy users curiosity.
